fix(home): rustdoc lint
See <https://github.com/rust-lang/cargo/actions/runs/32992508559/job/98253339881>

```
warning: redundant explicit link target
  --> crates/home/src/lib.rs:81:42
   |
81 | /// For more details, see [`cargo_home`](fn.cargo_home.html).
   |                            ------------  ^^^^^^^^^^^^^^^^^^ explicit target is redundant
   |                            |
   |                            because label contains path that resolves to same destination
   |
   = note: when a link's destination is not specified,
           the label is used to resolve intra-doc links
   = note: `#[warn(rustdoc::redundant_explicit_links)]` on by default
help: remove explicit link target
   |
81 - /// For more details, see [`cargo_home`](fn.cargo_home.html).
81 + /// For more details, see [`cargo_home`].
   |

warning: redundant explicit link target
   --> crates/home/src/lib.rs:118:43
    |
118 | /// For more details, see [`rustup_home`](fn.rustup_home.html).
    |                            -------------  ^^^^^^^^^^^^^^^^^^^ explicit target is redundant
    |                            |
    |                            because label contains path that resolves to same destination
    |
    = note: when a link's destination is not specified,
            the label is used to resolve intra-doc links
help: remove explicit link target
    |
118 - /// For more details, see [`rustup_home`](fn.rustup_home.html).
118 + /// For more details, see [`rustup_home`].
    |

error: `home` (lib doc) generated 2 warnings
```