Downgrade curl-sys to 0.4.83
With version 0.4.84, cargo was failing on FreeBSD 13.5 and 14.3 every
time, with errors like this:

```
    Updating crates.io index
error: failed to get `futures` as a dependency of package `tokio-file v0.11.0 (/tmp/cirrus-ci-build)`
Caused by:
  download of config.json failed
Caused by:
  failed to download from `https://index.crates.io/config.json`
Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL certificate OpenSSL verify result: unable to get local issuer certificate (20))
```

Fixes #16357