refactor(manifest): Remove unused 'profile.debug' suggestion
Instead we get
```
error: profile name `debug` is reserved
       To configure the default development profile, use the name `dev` as in [profile.dev]
       See https://doc.rust-lang.org/cargo/reference/profiles.html for more on configuring profiles.
  --> Cargo.toml:15:25
   |
15 |                [profile.debug]
   |                         ^^^^^
```