fix: we don't ignore `version` for `git`/`path` deps now
Here's a sample invocation using Cargo 1.48 to prove this:

```
$ cargo new test-cargo-version-path-constraints && cd test-cargo-version-path-constraints
     Created binary (application) `test-cargo-version-path-constraints` package

$ echo 'windows-service = { version = "999", git = "https://github.com/NZXTCorp/windows-service-rs" }' >> Cargo.toml

$ cargo build
    Updating git repository `https://github.com/NZXTCorp/windows-service-rs`
error: failed to select a version for the requirement `windows-service = "^999"`
candidate versions found which didn't match: 0.3.2
location searched: Git repository https://github.com/NZXTCorp/windows-service-rs
required by package `test-cargo-version-path-constraints v0.1.0 (C:\tools\msys64\home\erich\workspace\tmp\test-cargo-version-path-constraints)`
```