Make the error messaging for `cargo install` aware of `build.build-dir`
```
error: could not compile `issue-16622` (bin "issue-16622") due to 1 previous error
error: failed to compile `issue-16622 v0.0.0 ([…]/issue_16622)`, intermediate artifacts can be found at `[…]/issue_16622/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

currently points to the target directory.

However, intermediate artifacts are stored in the directory configured by `build.build-dir`,
so the message should be updated to point to that path and corresponding environment variable instead.