test: relax redaction for running `ssh`
`ssh` binary is not available on some platforms.

https://github.com/rust-lang-ci/rust/actions/runs/9814397548/job/27101968836#step:25:10940

```
---- git_auth::net_err_suggests_fetch_with_cli stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo check -v`
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo check -v`
thread 'git_auth::net_err_suggests_fetch_with_cli' panicked at tests/testsuite/git_auth.rs:439:10:

---- expected: tests/testsuite/git_auth.rs:415:27
++++ actual:   stderr
   1    1 | [UPDATING] git repository `ssh://needs-proxy.invalid/git`
   2    2 | [RUNNING] `git fetch --verbose --force --update-head-ok [..]ssh://needs-proxy.invalid/git[..] [..]+HEAD:refs/remotes/origin/HEAD[..]`
   3      - ssh: Could not resolve hostname needs-proxy.invalid: [..] not known
   4      - fatal: Could not read from remote repository.
   5      -
   6      - Please make sure you have the correct access rights
   7      - and the repository exists.
        3 + [ERROR] cannot run ssh: No such file or directory
        4 + fatal: unable to fork
   8    5 | [ERROR] failed to get `foo` as a dependency of package `foo v0.0.0 ([ROOT]/foo)`
   9    6 |
  10    7 | Caused by:
  11    8 |   failed to load source for dependency `foo`
  12    9 |
          ⋮
  15   12 |
  16   13 | Caused by:
  17   14 |   failed to fetch into: [ROOT]/home/.cargo/git/db/git-[HASH]
  18   15 |
  19   16 | Caused by:
  20      -   process didn't exit successfully: `git fetch --verbose --force --update-head-ok [..]ssh://needs-proxy.invalid/git[..] [..]+HEAD:refs/remotes/origin/HEAD[..]` ([EXIT_STATUS]: 128)
       17 +   process didn't exit successfully: `git fetch --verbose --force --update-head-ok 'ssh://needs-proxy.invalid/git' '+HEAD:refs/remotes/origin/HEAD'` ([EXIT_STATUS]: 128)
```