Cache submodules between different checkouts of the same git dep
This base64-encodes the URLs to avoid errors like the following:
```
error: failed to get `dep1` as a dependency of package `foo v0.5.0 (D:/a/cargo/cargo/target/tmp/cit/t1035/foo)`

Caused by:
  failed to load source for dependency `dep1`

Caused by:
  Unable to update file:///D:/a/cargo/cargo/target/tmp/cit/t1035/dep1

Caused by:
  failed to update submodule `src`

Caused by:
  failed to make directory 'D:/a/cargo/cargo/target/tmp/cit/t1035/home/.cargo/git/checkouts/submodules/file:': The filename, directory name, or volume label syntax is incorrect.
  ; class=Os (2)
', tests\testsuite\git.rs:2515:10
```

It uses bare checkouts instead of symbolic links to avoid permission errors on Windows.