Add tests of build script rerun on RUSTC_WRAPPER change
Currently fails on the "Reruns build script because RUSTC_WRAPPER
changes the fingerprint" step.

    ---- freshness::rerun_build_script_if_add_rustc_wrapper stdout ----
    running `/git/cargo/target/debug/cargo check`
    running `/git/cargo/target/debug/cargo check`
    running `/git/cargo/target/debug/cargo build`
    running `/git/cargo/target/debug/cargo check`
    thread 'freshness::rerun_build_script_if_add_rustc_wrapper' panicked at 'assertion failed: file_created_by_build_script.exists()', tests/testsuite/freshness.rs:888:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace