test(progress): Resolve flakiness
This is a follow up to #14181 which broke CI in #14221

```
---- progress::always_shows_progress stdout ----
running `/Users/runner/work/cargo/cargo/target/debug/cargo check`
thread 'progress::always_shows_progress' panicked at tests/testsuite/progress.rs:128:10:

---- expected: tests/testsuite/progress.rs:116:13
++++ actual:   stderr
   1    1 | [DOWNLOADING] 1 crate                                                                              
   2    2 | [DOWNLOADING] 2 crates                                                                             
   3    3 | [DOWNLOADING] 3 crates                                                                             
   4    4 | [DOWNLOADED] 3 crates ([..]KB) in [..]s
   5      - [BUILDING] [..] 0/4: [..]
   6    5 | [BUILDING] [..] 3/4: foo                                             
   7    6 | [FINISHED] `dev` profile [unoptimized + debuginfo] target(s) in [ELAPSED]s
   8    7 | ...∅

Update with SNAPSHOTS=overwrite
```